// Use this type collection because there are more than one place will use the same types.
// such as in action and reducer.

const types = {
    
    INITIALIZE_SESSION: 'INITIALIZE_SESSION',
    API_INITIALIZE_SESSION: 'API_INITIALIZE_SESSION',

    // Authorization
    REGISTER: 'REGISTER',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    API_REGISTER: 'API_REGISTER',
    API_LOGIN: 'API_LOGIN',
    API_LOGOUT: 'API_LOGOUT',

    // Collaborator
    ADD_NEW_COLLABORATOR: 'ADD_NEW_COLLABORATOR',
    RENAME_COLLABORATOR: 'RENAME_COLLABORATOR',
    DELETE_COLLABORATOR: 'DELETE_COLLABORATOR',
    API_ADD_NEW_COLLABORATOR: 'API_ADD_NEW_COLLABORATOR',
    API_RENAME_COLLABORATOR: 'API_RENAME_COLLABORATOR',
    API_DELETE_COLLABORATOR: 'API_DELETE_COLLABORATOR',

    // Resturants
    ADD_RESTAURANT_TO_COLLECTION: 'ADD_RESTAURANT_TO_COLLECTION',
    REMOVE_RESTAURANT_FROM_COLLECTION: 'REMOVE_RESTAURANT_FROM_COLLECTION',
    API_ADD_RESTAURANT_TO_COLLECTION: 'API_ADD_RESTAURANT_TO_COLLECTION',
    API_REMOVE_RESTAURANT_FROM_COLLECTION: 'API_REMOVE_RESTAURANT_FROM_COLLECTION',
    API_GET_RESTAURANTS: 'API_GET_RESTAURANTS',

    // collection
    SHOW_COLLECTION: 'SHOW_COLLECTION',
    ADD_NEW_COLLECTION: 'ADD_NEW_COLLECTION',
    DELETE_COLLECTION: 'DELETE_COLLECTION',
    API_ADD_NEW_COLLECTION: 'API_ADD_NEW_COLLECTION',
    API_DELETE_COLLECTION: 'API_DELETE_COLLECTION',

    // event trigger
    SHOW_POPUP: 'SHOW_POPUP',
    RESET_POPUP: 'RESET_POPUP',
}

export default types;